# 公共配置文件
server:
  port: 8090
spring:
  application:
    name: qiapi-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      # 网关全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
      default-filters:
        - AddResponseHeader=source, rickey
      # 'requestFrom': 'Frontend', // 添加请求头，表示请求是从前端发出的
      # 断言设计，目前有backend,interface,order,thirdParty
      routes:
        - id: order
          uri: http://localhost:7530
          predicates:
            - Path=/api/order/**
        - id: thirdParty
          uri: http://localhost:7531
          predicates:
            - Path=/api/thirdParty/**
        - id: interfaceInvoke
          uri: http://localhost:8123
          predicates:
            - Path=/api/interfaceInvoke/**
        - id: backend
          uri: http://localhost:7529
          predicates:
            - Path=/api/**

  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    type: redis

logging:
  level:
    org.apache.dubbo: DEBUG

dubbo:
  application:
    name: qiapi-gateway
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20881
