# 公共配置文件
server:
  port: 8090
spring:
  application:
    name: qiapi-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, rickey
      # 断言设计，目前有backend,interface,order,thirdParty
      routes:
        - id: order
          uri: http://localhost:7531
          predicates:
            - Path=/api/order
        - id: thirdParty
          uri: http://localhost:7530
          predicates:
            - Path=/api/thirdParty
#        - id: interface
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/interface
        - id: backend
          uri: http://localhost:7529
          predicates:
            - Path=/api/**
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    type: redis

logging:
  level:
    org.apache.dubbo: DEBUG

dubbo:
  application:
    name: qiapi-gateway
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20880
