# 公共配置文件
server:
  port: 8123
  servlet:
    context-path: /api/interfaceInvoke
spring:
  application:
    name: qiapi-interfaceInvoke
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qiapi
    username: root
    password: 123456
  cloud:
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: localhost:8880
        port: 8723
        clientIp: localhost
      filter:
        url-patterns: /**
      web-context-unify: false
    nacos:
      discovery:
        server-addr: localhost:8848



